import type { Metadata } from "next";
import "./globals.css";
import { PhotoProvider } from "./Context/PhotoContext";
import { Poppins } from "next/font/google";
// import localFont from "next/font/local";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700"], // weights
  subsets: ["latin"],
  fallback: ["sans-serif"], // fallback font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PhotoProvider>
        <body className={poppins.className}>{children}</body>
      </PhotoProvider>
    </html>
  );
}
